/* eslint-disable */
// AUTO-GENERATED by config/scripts/generate-orca-skill-reference-hashes.mjs
// Do not edit by hand. Re-run the script after changing managed skills/*/SKILL.md.
// Why: package freshness without shipping the skills/ tree into the app bundle.

export const ORCA_SKILL_REFERENCE_HASHES: Readonly<Record<string, string>> = Object.freeze({
  'orca-cli': 'b4c36e19fc158fc8c286bdfdf05a537985cb2159a596c93862968c5417bf15be',
  orchestration: '0cb898d37560ab7ac4cb477a2d7e8ba3e593d45affd6d7e9f99151879aaeb1a5',
  'computer-use': 'f49b29fb6b209956907688692387adcdc509fad344555f09badaf383106f5f39',
  'orca-per-workspace-env': '58e479bd18c4c553df0dfcb408eece2fbe550a0f9688bc289414420f72ed7ea7'
})
